parameters:
- name: commitMessage
  type: string
  displayName: 'Commit message for exported changes'

stages:
  - stage: Export
    displayName: 'Export'
    jobs:
      - job: ExportJob
        displayName: 'Export'
        steps:
        - checkout: self
          persistCredentials: true
          fetchDepth: 1
          displayName: 'Checkout Source Code'
          path: self
          
        - checkout: ALM4Dataverse
          fetchDepth: 1
          displayName: 'Checkout ALM Templates Repository'
          path: alm

        - task: PowerPlatformToolInstaller@2
          displayName: 'Install Power Platform Tools'
          inputs:
            AddToolsToPath: true

        - task: PowerPlatformSetConnectionVariables@2
          displayName: 'Set Connection Variables'
          name: connectionVariables
          inputs:
            authenticationType: 'PowerPlatformSPN'
            PowerPlatformSPN: Dev-${{ variables['Build.SourceBranchName'] }}

        - pwsh: |
              & "$(Pipeline.Workspace)/alm/pipelines/scripts/installdependencies.ps1"
              & "$(Pipeline.Workspace)/alm/pipelines/scripts/connect.ps1" -ConnectionString "$(connectionVariables.BuildTools.DataverseConnectionString)"
              & "$(Pipeline.Workspace)/alm/pipelines/scripts/export.ps1" `
                -SourceDirectory "$(Pipeline.Workspace)/self" `
                -ArtifactStagingDirectory "$(Build.ArtifactStagingDirectory)" `
                -TempDirectory "$(Agent.TempDirectory)" `
                -EnvironmentName "Dev-${{ variables['Build.SourceBranchName'] }}"
          displayName: 'Connect and Export Solutions'
          workingDirectory: '$(Pipeline.Workspace)/self'

        - pwsh: |
            $ErrorActionPreference = 'Stop'
            git config user.email "$(Build.RequestedForEmail)"
            if ($LASTEXITCODE -ne 0) { throw "git config user.email failed with exit code $LASTEXITCODE" }
            git config user.name "$(Build.RequestedFor)"
            if ($LASTEXITCODE -ne 0) { throw "git config user.name failed with exit code $LASTEXITCODE" }
            git add .
            if ($LASTEXITCODE -ne 0) { throw "git add failed with exit code $LASTEXITCODE" }
            git commit -m "${{ parameters.commitMessage }}"
            if ($LASTEXITCODE -eq 0) {
                # Committed successfully
            } elseif ($LASTEXITCODE -eq 1) {
                Write-Host "No changes to commit"
            } else {
                throw "git commit failed with exit code $LASTEXITCODE"
            }
            git push origin HEAD:$(Build.SourceBranch)
            if ($LASTEXITCODE -ne 0) { throw "git push failed with exit code $LASTEXITCODE" }
          displayName: 'Commit Changes'
          workingDirectory: '$(Pipeline.Workspace)/self'
