trigger: none # Triggered by build completion or manually

resources:
  pipelines:
    - pipeline: build
      source: 'BUILD'
      trigger:
        branches:
          include:
          - main
  repositories:
    - repository: ALM4Dataverse
      type: git
      name: ALM4Dataverse


name: 'Deploy $(resources.pipeline.build.runName)'
appendCommitMessageToRunName: false

stages:
  
  # Example - uncomment and repeat for each environment to deploy to

  # - template: pipelines/templates/stages/deploy-environment.yml@ALM4Dataverse
  #   parameters:
  #     environmentName: Test-main